name: gh-pages

on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    
    - name: Publish with dotnet
      run: dotnet publish --configuration Release --output build --nologo
    
    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/amzn-bkmt\/" \/>/g' build.wwwroot/index.html

    - name: Add .nojekyll file
      run: touch build.wwwroot/.nojekyll

    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/wwwroot